defaults:
  - _self_

# Data settings
data:
  path: "data/output/featured_data.csv"  # Single unified dataset
  target_column: "target"
  price_column: "price(SGD)"

# Training settings
training:
  horizons: [1, 2, 3, 4, 5, 6, 7]
  models: ["lightgbm", "xgboost", "random_forest", "linear", "ridge"]
  # models: ["lightgbm", "xgboost", "random_forest","linear","ridge","lstm"]  # TODO: implement LSTM
  test_size: 0.2      # Last 20% of each watch's data
  val_size: 0.1       # 10% before test set
  random_state: 42
  max_samples: null   # Set to limit data size

# Model hyperparameters
models:
  lightgbm:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: -1
    num_leaves: 31
    early_stopping_rounds: 10
  xgboost:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    early_stopping_rounds: 10
  random_forest:
    n_estimators: 100
    max_depth: null
  linear:
    fit_intercept: true
  ridge:
    alpha: 1.0
  lasso:
    alpha: 1.0

# Output settings
output:
  base_dir: "data/output/models"
  save_models: true
  save_predictions: true
